<?xml version="1.0"?>
<robot xmlns:xacro="http://wiki.ros.org/xacro" name="custom_mobile_manipulator">

  <!-- Define robot constants -->
  <xacro:property name="base_width" value="0.4"/>
  <xacro:property name="base_length" value="0.6"/>
  <xacro:property name="base_height" value="0.2"/>
  <xacro:property name="wheel_radius" value="0.1"/>
  <xacro:property name="wheel_width" value="0.04"/>
  <xacro:property name="wheel_separation" value="0.45"/>
  <xacro:property name="caster_radius" value="0.05"/>

  <!-- Define inertial macros -->
  <xacro:macro name="box_inertia" params="m w h d">
    <inertial>
      <mass value="${m}"/>
      <inertia ixx="${m*(h*h+d*d)/12}" ixy="0" ixz="0"
               iyy="${m*(w*w+d*d)/12}" iyz="0"
               izz="${m*(w*w+h*h)/12}"/>
    </inertial>
  </xacro:macro>

  <xacro:macro name="cylinder_inertia" params="m r h">
    <inertial>
      <mass value="${m}"/>
      <inertia ixx="${m*(3*r*r+h*h)/12}" ixy="0" ixz="0"
               iyy="${m*(3*r*r+h*h)/12}" iyz="0"
               izz="${m*r*r/2}"/>
    </inertial>
  </xacro:macro>

  <xacro:macro name="sphere_inertia" params="m r">
    <inertial>
      <mass value="${m}"/>
      <inertia ixx="${2*m*r*r/5}" ixy="0" ixz="0"
               iyy="${2*m*r*r/5}" iyz="0"
               izz="${2*m*r*r/5}"/>
    </inertial>
  </xacro:macro>

  <!-- Base Link -->
  <link name="base_footprint"/>

  <link name="base_link">
    <visual>
      <geometry>
        <box size="${base_length} ${base_width} ${base_height}"/>
      </geometry>
      <material name="blue">
        <color rgba="0.2 0.2 1.0 1.0"/>
      </material>
    </visual>
    <collision>
      <geometry>
        <box size="${base_length} ${base_width} ${base_height}"/>
      </geometry>
    </collision>
    <xacro:box_inertia m="10" w="${base_length}" h="${base_width}" d="${base_height}"/>
  </link>

  <joint name="base_footprint_joint" type="fixed">
    <parent link="base_footprint"/>
    <child link="base_link"/>
    <origin xyz="0 0 ${wheel_radius + base_height/2}" rpy="0 0 0"/>
  </joint>

  <!-- Wheels -->
  <xacro:macro name="wheel" params="prefix y_offset">
    <link name="${prefix}_wheel">
      <visual>
        <geometry>
          <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
        </geometry>
        <material name="black">
          <color rgba="0.1 0.1 0.1 1.0"/>
        </material>
      </visual>
      <collision>
        <geometry>
          <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
        </geometry>
      </collision>
      <xacro:cylinder_inertia m="1" r="${wheel_radius}" h="${wheel_width}"/>
    </link>

    <joint name="${prefix}_wheel_joint" type="continuous">
      <parent link="base_link"/>
      <child link="${prefix}_wheel"/>
      <origin xyz="0 ${y_offset} ${-base_height/2}" rpy="${pi/2} 0 0"/>
      <axis xyz="0 0 1"/>
      <limit effort="10" velocity="10"/>
    </joint>
  </xacro:macro>

  <xacro:wheel prefix="left" y_offset="${wheel_separation/2}"/>
  <xacro:wheel prefix="right" y_offset="${-wheel_separation/2}"/>

  <!-- Front Caster -->
  <link name="front_caster">
    <visual>
      <geometry>
        <sphere radius="${caster_radius}"/>
      </geometry>
      <material name="gray">
        <color rgba="0.5 0.5 0.5 1.0"/>
      </material>
    </visual>
    <collision>
      <geometry>
        <sphere radius="${caster_radius}"/>
      </geometry>
    </collision>
    <xacro:sphere_inertia m="0.5" r="${caster_radius}"/>
  </link>

  <joint name="front_caster_joint" type="fixed">
    <parent link="base_link"/>
    <child link="front_caster"/>
    <origin xyz="${base_length/2 - caster_radius} 0 ${-base_height/2 - caster_radius + wheel_radius}" rpy="0 0 0"/>
  </joint>

  <!-- Rear Caster -->
  <link name="rear_caster">
    <visual>
      <geometry>
        <sphere radius="${caster_radius}"/>
      </geometry>
      <material name="gray">
        <color rgba="0.5 0.5 0.5 1.0"/>
      </material>
    </visual>
    <collision>
      <geometry>
        <sphere radius="${caster_radius}"/>
      </geometry>
    </collision>
    <xacro:sphere_inertia m="0.5" r="${caster_radius}"/>
  </link>

  <joint name="rear_caster_joint" type="fixed">
    <parent link="base_link"/>
    <child link="rear_caster"/>
    <origin xyz="${-base_length/2 + caster_radius} 0 ${-base_height/2 - caster_radius + wheel_radius}" rpy="0 0 0"/>
  </joint>

  <!-- Manipulator Arm -->
  <!-- Shoulder -->
  <link name="shoulder_link">
    <visual>
      <geometry>
        <cylinder radius="0.05" length="0.1"/>
      </geometry>
      <material name="orange">
        <color rgba="1.0 0.5 0.0 1.0"/>
      </material>
    </visual>
    <collision>
      <geometry>
        <cylinder radius="0.05" length="0.1"/>
      </geometry>
    </collision>
    <xacro:cylinder_inertia m="1" r="0.05" h="0.1"/>
  </link>

  <joint name="shoulder_pan_joint" type="revolute">
    <parent link="base_link"/>
    <child link="shoulder_link"/>
    <origin xyz="0.15 0 ${base_height/2 + 0.05}" rpy="0 0 0"/>
    <axis xyz="0 0 1"/>
    <limit lower="-${pi}" upper="${pi}" effort="50" velocity="1.0"/>
  </joint>

  <!-- Upper Arm -->
  <link name="upper_arm_link">
    <visual>
      <origin xyz="0.15 0 0" rpy="0 ${pi/2} 0"/>
      <geometry>
        <cylinder radius="0.04" length="0.3"/>
      </geometry>
      <material name="orange">
        <color rgba="1.0 0.5 0.0 1.0"/>
      </material>
    </visual>
    <collision>
      <origin xyz="0.15 0 0" rpy="0 ${pi/2} 0"/>
      <geometry>
        <cylinder radius="0.04" length="0.3"/>
      </geometry>
    </collision>
    <xacro:cylinder_inertia m="0.8" r="0.04" h="0.3"/>
  </link>

  <joint name="shoulder_lift_joint" type="revolute">
    <parent link="shoulder_link"/>
    <child link="upper_arm_link"/>
    <origin xyz="0 0 0.05" rpy="0 0 0"/>
    <axis xyz="0 1 0"/>
    <limit lower="-${pi/2}" upper="${pi/2}" effort="50" velocity="1.0"/>
  </joint>

  <!-- Forearm -->
  <link name="forearm_link">
    <visual>
      <origin xyz="0.125 0 0" rpy="0 ${pi/2} 0"/>
      <geometry>
        <cylinder radius="0.035" length="0.25"/>
      </geometry>
      <material name="orange">
        <color rgba="1.0 0.5 0.0 1.0"/>
      </material>
    </visual>
    <collision>
      <origin xyz="0.125 0 0" rpy="0 ${pi/2} 0"/>
      <geometry>
        <cylinder radius="0.035" length="0.25"/>
      </geometry>
    </collision>
    <xacro:cylinder_inertia m="0.6" r="0.035" h="0.25"/>
  </link>

  <joint name="elbow_joint" type="revolute">
    <parent link="upper_arm_link"/>
    <child link="forearm_link"/>
    <origin xyz="0.3 0 0" rpy="0 0 0"/>
    <axis xyz="0 1 0"/>
    <limit lower="-${pi}" upper="0" effort="30" velocity="1.0"/>
  </joint>

  <!-- Wrist -->
  <link name="wrist_link">
    <visual>
      <geometry>
        <cylinder radius="0.03" length="0.05"/>
      </geometry>
      <material name="gray">
        <color rgba="0.5 0.5 0.5 1.0"/>
      </material>
    </visual>
    <collision>
      <geometry>
        <cylinder radius="0.03" length="0.05"/>
      </geometry>
    </collision>
    <xacro:cylinder_inertia m="0.3" r="0.03" h="0.05"/>
  </link>

  <joint name="wrist_joint" type="continuous">
    <parent link="forearm_link"/>
    <child link="wrist_link"/>
    <origin xyz="0.25 0 0" rpy="0 ${pi/2} 0"/>
    <axis xyz="0 0 1"/>
    <limit effort="10" velocity="1.0"/>
  </joint>

  <!-- Gripper -->
  <link name="gripper_base">
    <visual>
      <geometry>
        <box size="0.05 0.08 0.02"/>
      </geometry>
      <material name="gray">
        <color rgba="0.5 0.5 0.5 1.0"/>
      </material>
    </visual>
    <collision>
      <geometry>
        <box size="0.05 0.08 0.02"/>
      </geometry>
    </collision>
    <xacro:box_inertia m="0.1" w="0.05" h="0.08" d="0.02"/>
  </link>

  <joint name="gripper_base_joint" type="fixed">
    <parent link="wrist_link"/>
    <child link="gripper_base"/>
    <origin xyz="0.035 0 0" rpy="0 0 0"/>
  </joint>

  <!-- Gripper Fingers -->
  <link name="left_finger">
    <visual>
      <origin xyz="0.02 0 0" rpy="0 0 0"/>
      <geometry>
        <box size="0.04 0.01 0.02"/>
      </geometry>
      <material name="red">
        <color rgba="1.0 0.0 0.0 1.0"/>
      </material>
    </visual>
    <collision>
      <origin xyz="0.02 0 0" rpy="0 0 0"/>
      <geometry>
        <box size="0.04 0.01 0.02"/>
      </geometry>
    </collision>
    <xacro:box_inertia m="0.05" w="0.04" h="0.01" d="0.02"/>
  </link>

  <joint name="left_finger_joint" type="prismatic">
    <parent link="gripper_base"/>
    <child link="left_finger"/>
    <origin xyz="0.025 0.02 0" rpy="0 0 0"/>
    <axis xyz="0 1 0"/>
    <limit lower="0" upper="0.025" effort="10" velocity="0.1"/>
  </joint>

  <link name="right_finger">
    <visual>
      <origin xyz="0.02 0 0" rpy="0 0 0"/>
      <geometry>
        <box size="0.04 0.01 0.02"/>
      </geometry>
      <material name="red">
        <color rgba="1.0 0.0 0.0 1.0"/>
      </material>
    </visual>
    <collision>
      <origin xyz="0.02 0 0" rpy="0 0 0"/>
      <geometry>
        <box size="0.04 0.01 0.02"/>
      </geometry>
    </collision>
    <xacro:box_inertia m="0.05" w="0.04" h="0.01" d="0.02"/>
  </link>

  <joint name="right_finger_joint" type="prismatic">
    <parent link="gripper_base"/>
    <child link="right_finger"/>
    <origin xyz="0.025 -0.02 0" rpy="0 0 0"/>
    <axis xyz="0 -1 0"/>
    <limit lower="0" upper="0.025" effort="10" velocity="0.1"/>
    <mimic joint="left_finger_joint" multiplier="1" offset="0"/>
  </joint>

  <!-- Gazebo ROS2 Control Plugin -->
  <ros2_control name="GazeboSimSystem" type="system">
    <hardware>
      <plugin>gz_ros2_control/GazeboSimSystem</plugin>
    </hardware>

    <!-- Differential Drive -->
    <joint name="left_wheel_joint">
      <command_interface name="velocity"/>
      <state_interface name="position"/>
      <state_interface name="velocity"/>
    </joint>

    <joint name="right_wheel_joint">
      <command_interface name="velocity"/>
      <state_interface name="position"/>
      <state_interface name="velocity"/>
    </joint>

    <!-- Arm Joints -->
    <joint name="shoulder_pan_joint">
      <command_interface name="position"/>
      <state_interface name="position"/>
      <state_interface name="velocity"/>
    </joint>

    <joint name="shoulder_lift_joint">
      <command_interface name="position"/>
      <state_interface name="position"/>
      <state_interface name="velocity"/>
    </joint>

    <joint name="elbow_joint">
      <command_interface name="position"/>
      <state_interface name="position"/>
      <state_interface name="velocity"/>
    </joint>

    <joint name="wrist_joint">
      <command_interface name="position"/>
      <state_interface name="position"/>
      <state_interface name="velocity"/>
    </joint>

    <!-- Gripper -->
    <joint name="left_finger_joint">
      <command_interface name="position"/>
      <state_interface name="position"/>
      <state_interface name="velocity"/>
    </joint>
  </ros2_control>

  <gazebo>
    <plugin filename="gz_ros2_control-system" name="gz_ros2_control::GazeboSimROS2ControlPlugin">
      <parameters>$(find custom_robot_gz)/config/custom_robot_controllers.yaml</parameters>
    </plugin>
  </gazebo>

</robot>